// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCssIj3RbVVgMtv9f0EbxOCVUR2k8HkC4Q',
    appId: '1:950705745384:web:be79fd1d221ee6709f485d',
    messagingSenderId: '950705745384',
    projectId: 'authentification-1a13d',
    authDomain: 'authentification-1a13d.firebaseapp.com',
    storageBucket: 'authentification-1a13d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-4Vnjw29xlQCFJRyUXmyuYqpJaPS3o0E',
    appId: '1:950705745384:android:55c31190923d38989f485d',
    messagingSenderId: '950705745384',
    projectId: 'authentification-1a13d',
    storageBucket: 'authentification-1a13d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmMw26HTb3CKXTgPS1cIC36mmqWVQDAQc',
    appId: '1:950705745384:ios:538e0b01bde77d0e9f485d',
    messagingSenderId: '950705745384',
    projectId: 'authentification-1a13d',
    storageBucket: 'authentification-1a13d.firebasestorage.app',
    iosBundleId: 'com.example.authentification2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmMw26HTb3CKXTgPS1cIC36mmqWVQDAQc',
    appId: '1:950705745384:ios:538e0b01bde77d0e9f485d',
    messagingSenderId: '950705745384',
    projectId: 'authentification-1a13d',
    storageBucket: 'authentification-1a13d.firebasestorage.app',
    iosBundleId: 'com.example.authentification2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCssIj3RbVVgMtv9f0EbxOCVUR2k8HkC4Q',
    appId: '1:950705745384:web:ec314f5e1a1400ee9f485d',
    messagingSenderId: '950705745384',
    projectId: 'authentification-1a13d',
    authDomain: 'authentification-1a13d.firebaseapp.com',
    storageBucket: 'authentification-1a13d.firebasestorage.app',
  );
}
