// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI67Y4H9khKhy_GEmgUFMPl7U0gnSvjQY',
    appId: '1:525454913221:web:526c95d36f7e9fc5e34aac',
    messagingSenderId: '525454913221',
    projectId: 'studyflow-15d2c',
    authDomain: 'studyflow-15d2c.firebaseapp.com',
    storageBucket: 'studyflow-15d2c.firebasestorage.app',
    measurementId: 'G-BJ9HTQD8HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZuDwvKjwdc7GEXljWImodxfzY-CfT6OI',
    appId: '1:525454913221:android:071f1a711f9d7f69e34aac',
    messagingSenderId: '525454913221',
    projectId: 'studyflow-15d2c',
    storageBucket: 'studyflow-15d2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ELPgRDAwxTClbvNNolR_UPZCiMT0Cvs',
    appId: '1:525454913221:ios:39c8b257b5e90564e34aac',
    messagingSenderId: '525454913221',
    projectId: 'studyflow-15d2c',
    storageBucket: 'studyflow-15d2c.firebasestorage.app',
    iosBundleId: 'com.example.studyFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5ELPgRDAwxTClbvNNolR_UPZCiMT0Cvs',
    appId: '1:525454913221:ios:39c8b257b5e90564e34aac',
    messagingSenderId: '525454913221',
    projectId: 'studyflow-15d2c',
    storageBucket: 'studyflow-15d2c.firebasestorage.app',
    iosBundleId: 'com.example.studyFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI67Y4H9khKhy_GEmgUFMPl7U0gnSvjQY',
    appId: '1:525454913221:web:9637d70c0910f9bee34aac',
    messagingSenderId: '525454913221',
    projectId: 'studyflow-15d2c',
    authDomain: 'studyflow-15d2c.firebaseapp.com',
    storageBucket: 'studyflow-15d2c.firebasestorage.app',
    measurementId: 'G-1G26S7K3WJ',
  );
}
