// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt-DwqZ49F1DOvDVBhT9pJELGDXZDnGww',
    appId: '1:770408977433:web:7ccfd872a87816bcf9c688',
    messagingSenderId: '770408977433',
    projectId: 'shoevaultproject',
    authDomain: 'shoevaultproject.firebaseapp.com',
    storageBucket: 'shoevaultproject.firebasestorage.app',
    measurementId: 'G-BFQ4X2CSR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF_EFyA2Ie7shZhWeurnFVsaGKuBVfF78',
    appId: '1:770408977433:android:701216ffb0db7dc1f9c688',
    messagingSenderId: '770408977433',
    projectId: 'shoevaultproject',
    storageBucket: 'shoevaultproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXvXADpK1u72rw9N8Q6HcI8rgsTxwhA1E',
    appId: '1:770408977433:ios:3fa981c779ab14dff9c688',
    messagingSenderId: '770408977433',
    projectId: 'shoevaultproject',
    storageBucket: 'shoevaultproject.firebasestorage.app',
    iosBundleId: 'com.example.shoeVaultProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXvXADpK1u72rw9N8Q6HcI8rgsTxwhA1E',
    appId: '1:770408977433:ios:3fa981c779ab14dff9c688',
    messagingSenderId: '770408977433',
    projectId: 'shoevaultproject',
    storageBucket: 'shoevaultproject.firebasestorage.app',
    iosBundleId: 'com.example.shoeVaultProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt-DwqZ49F1DOvDVBhT9pJELGDXZDnGww',
    appId: '1:770408977433:web:9db8e38b01b93ec4f9c688',
    messagingSenderId: '770408977433',
    projectId: 'shoevaultproject',
    authDomain: 'shoevaultproject.firebaseapp.com',
    storageBucket: 'shoevaultproject.firebasestorage.app',
    measurementId: 'G-MHDCSKCJRF',
  );
}
