// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrcetDve34E3_efLVd61bXyFm6x-oFHVY',
    appId: '1:841071693712:web:dbfe415d6a8df915966d15',
    messagingSenderId: '841071693712',
    projectId: 'fir-crud-basics-1e487',
    authDomain: 'fir-crud-basics-1e487.firebaseapp.com',
    storageBucket: 'fir-crud-basics-1e487.firebasestorage.app',
    measurementId: 'G-L8H0LXKQLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJTsBguQQ2fdnn_3B6WUFnpNr944ZoH_k',
    appId: '1:841071693712:android:4284a833be43650c966d15',
    messagingSenderId: '841071693712',
    projectId: 'fir-crud-basics-1e487',
    storageBucket: 'fir-crud-basics-1e487.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiVrcFZR8Lpj7g5NuNqbHpdOzONeJGXQU',
    appId: '1:841071693712:ios:9bc5bb8e7f6fcb18966d15',
    messagingSenderId: '841071693712',
    projectId: 'fir-crud-basics-1e487',
    storageBucket: 'fir-crud-basics-1e487.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiVrcFZR8Lpj7g5NuNqbHpdOzONeJGXQU',
    appId: '1:841071693712:ios:9bc5bb8e7f6fcb18966d15',
    messagingSenderId: '841071693712',
    projectId: 'fir-crud-basics-1e487',
    storageBucket: 'fir-crud-basics-1e487.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrcetDve34E3_efLVd61bXyFm6x-oFHVY',
    appId: '1:841071693712:web:b056a1a257e5ebe5966d15',
    messagingSenderId: '841071693712',
    projectId: 'fir-crud-basics-1e487',
    authDomain: 'fir-crud-basics-1e487.firebaseapp.com',
    storageBucket: 'fir-crud-basics-1e487.firebasestorage.app',
    measurementId: 'G-XPD9HSCRK8',
  );
}
